language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: HEZqOnYZHEUnGycV/ocbZWL2JUh9T6NXw5RSvnbxBwIcwp3v8xQTVOi4+KjBnvhUZW2FSgEu+k8t4cAlBeoU4RyHIVDKh10EO7mPgNonfAXqKsNeeJU8iaux0e2P1OS/VDcDJQucejtc9yvy/deJO5Xv44+A+y9E5HwCnEfZYn66I3RXzzqNaL0DDUGGzBxrJXJ0ImebsVppxZ7rHMUrYp2Ai1x9c0Xie3F/yX92bOfpJdeuBaWvJxHm0S7OIPoCrcZuNRsFR7jtS13L5QIShf/92oOosMEPDJgkS3WXxw6kRwVec7Li+TTFQjEyAP79+nr86c5DsoOPSbtFwX6AA8v6nMmV13sZbbgcpnMTq10yiviDNYmVQREGRGPxxChX5AFuatr3s1HHzNmDt5Nt206uhlLuFcudxiR885f+nX9PuHdlNb7AZNqku4WKKPC0emkuyUpbS+catUlzOsoqOp+E5q5K6ngwfBLDuaKJ/yecInxL5pKUpoYYHWCHefK9CoXQGzw+B2rsBc+fKwtcGJLltWViF9x2fOBEb76eZavS2vZdSOf7UYsXB3KS8ZMXuwZqcKsXJnX9gBtb+PAFaqkchKy8867jOg+vERmZw8I4yivNjlgy0vuxzg5JeK24dF2Bmekd3FWGAAPh4isPOOeOGlOrTINQ38uCLtHYjBo=
  app: portfolio-website
  on:
    repo: kcheco/portfolio-website
