language: ruby
install:
- bundle update --bundler
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: T1CJU5q12iLs14VcAO5Y0q9NerCVhAcRltrG0j348MS7jRq+pGoNp0DjwTg0r8rWlg0enz7iesz/bXyTPCIz4lfh+zZqxaF3bmtVEB69fRtKnYD52HYhCWQO5XwsOQ3yykOGFB0uLe5+YhH9NYVapO3lXF9zKLVPmGNW45rIyo4P80j+FvBx+HgXaLXW9kJsw63zxkxAb+OswAtDs4sXcjRL0ZFezW8guNKlZ+eIi/3JVqdR/C/NyjmLZ56hnpLd7g0ntdUx2NBFW3pU3mDiHpwJnBoiiHe3Bbg0hsjIW1ezPvTVM3kwKJxViQvb2tJBq4RBCYs26Jef4YTIW0pxQ0BoF7Jm0OpNJ9ah9IDp6Ce0CkF8f+g+iofFXxCHILPrc7PBrB+vI1K0WFcLbHyopTqxCDAv6dVnrc2ZLKNzA6o7pRpmlq3TW5g/lJ0Xbg/ma6nSNeayw2U8481DaYyfJe/Vm6bcV7tUn3w5hjPICTbdv19yA1ROOeUFhjLz1Hs/BejdzPMQK5SNPreMiKMcTjGtJdz0ofDCjpKqSCEflRWMXNsTuyqmvGdy4vv4rp92/tOIhLETy0V9OLcT8vQzcQyoWqkP0aVwHXpiKKwgtLOmZddit7hZBWvZid9mPlhb8KDJZLEF8we+LL2v/JIAMvOCmdXISbjkn5quBWGvBeo=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
