language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: hTCF3zdmMmC+DiBJ6fZescW7QAMUF8IzHFX2Uit/M9UPYhZBXqQcYc7mv8c89pq77qK5G0Z7WnoVdf9r0jv+qCVKJQ76dlExu/nFHpWfR9XQbDd+4uoZ33G7oc5uUXEX1t4/JQwnBXjxypkkuav2K7CfwO4Y5t2DrraG82r7e+J7pksZVXozIiWvLyVpuTTsrcD7fBP9S5XgOPvhV0ctbMKT/80zBv9ncdtbaFp5FV4K6F9I3UhFwy+6GAzfnbSLZYJbtdLEA3H0BGBreqfn3k8kEorBdZkAFjIik0qrJ5kZpIO1D3bjz8h49p2UlAkUxaNbm/Tk1kfGhRT3Nigp/y7FtqzYm1mQZTRkwVQr+k+tmSY2ZIgeA54iTI0revNpaGSl6mczUHY2j2cqFBsptphO4wZduk0ean8I5MuYaqs6n92xDY/GubFsobbQ604BTVBAEco5xzEUJup1b6YX3xVd8C080fWEHP7+bSuUeWflKFtUaNMCnqrox0YTe18X3CstXNKf8zDdgQsPkP4RT8NmJuTNYjZ9/XeDP3W7IVMJ2L2j/NUlln0hbA1tOQKsZy7tAaFNoDOlpbeKO2S2fUGVLhN3piR06pZdYx0EMo8aVsJVHX5gd/T1k//IeYvlK5Gdcy8VEiqNkpjt4P3NLgK1WF8FKMA2halA+CWG+fo=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
