language: ruby
install:
- bundle update --bundler
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: HO9Rbhn+6SUoiz7h6Kw0wBuKAEydiNmNh+rjrD0k4+PouwS6peZp5FLC1BQojguh1BvnDnYVsdzRHpmJ7pSL6IAVYJCPEAItluwlAAyUyIlzUTDwL2j5fPRhiR5VUyDpOlL9Gs9PsjzlRhkZYQ74KZPr5gZVTI2J9mosU2lgp0KkCqc1ITTom1vmOMoE3tgZXwCuP5/J8njDBtcVTBfg6mXCHh1+Czf07dsC+1QuVVESsH09dEaSkDtA7sm9ddl8bM5esiSA67RV7y3lzSDauex6djsMmDthc4/D73qTWtpspZrjpgrCOjozTHmvTwu3UF1P+LctGVShqQTjw+rdCLdeculuUn+y/UXnSWom5J8hNo+cRkH1P9YB443FWW8DqOOO0JyTvzSvxphLPmqXaT2PXq4bUhJA/kkkqSyhygg4cHUpe2ikXhUuCSkPw5slD7WQAa1JsPNyY5joRTS05ePGQFb3Y6LsEiKEQfH3Qre6CehJ22ImuevDETpB9duD9RKcLr3SCHD8R7JWBi3f45wVn09B3E9Tyt3V4Xj/SKZ660SMg4XehM6lqcJIE7vdtd8Y55zWz4Q5PxulFWvnz1ZlGnGCFFiGQldTtwVlwpmsSTLADL/wXpEodx7BmtG09DYaitmH5g0OAHPFp3glbeMUZnNLR2HWJy1zRjEnYpg=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
