language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: LGv+5GQgAkKyGT+f4Tvqj2WCdd+8tJgBNw3yWDMcbS96bI0LGvNNcjIuMaFMtUTxA/a7ZtFRuKN5HlCsDAhH588qXhB5QVnGfkzjHrdvxjSukOPF7m3UOzDFvMLK+GqKGMRlss1jOqbCQQ/2bOmc9w1o7XEMEAqpRHvj80fdug5HHgi3YQLycERPfjbBNRP/qZwm2dRI+gmYyhyMRZZxfbeBYHkpvrXkxTZlI4i7YLR9d6CibsPCWd3IdfDgXrxQiqkoGh0Fx8nbRbPoFDeEfYjqDscs7Dkiz/QGV0bw+0o/QUHx2WIWuRs0x4nDphoINVt5EedTOaMSRhcVx3OUoXT2X3AWffbfLKFvt9hPzz9DZ3AVfli6HudIEH5rr9qTt7DPwGU/YelhLZRcUjeKDHeeCOCem9VnbrJOW10hnrEOGJKkUAD9yJ/mykl3z+t8sXEebtnnha+vAL8mXvp+sBtR2Y3Ihkq9WnAHClY9eDd/v8+34SjQYP9T+cOw5t6OZHhqtXL1SavIjzgYLFcRpv8fSi+BYXn8Zjh+ZRDD/W54AkolyfSrGvyLc570/d4IwYaLCRDbv6gxJxcpaVJd+tsez7JnwM7uRet/HxFhuM5lz0VT3DQKnszX6Yz350vytHbPx52HNO15lwE4Zi/cII02qy8AUnqeI1wPUaEwdIc=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
