language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: gtwGrX0IOa8+kKjbGjzgqrc5ROOYH+3hE+0kor9s8yzI2whcvOVNs2AL5WOn3R9JuowsZfJB9qtSL5hEUuwt4qfzvfQ0g8LBakrl55UXia9sivsejE79Gt3AHYiG6NgNZJobktxGE3ZV8hOfje1Au1s+slQk4PMoixX4a7A64ok47fMjcpFtB8Q0q2RzC+QhU3jwJXvxzfoyizq2RuivLc+ExH/PLc0K9SBQd/mRNTm6Hz9vnik8vp/mRXGK5gQav6l7VB1zvbXwMikI5ir9LC+mfLv7NqjalUtrBeVBh/ZoP0mhCtMddD+LZFX0jYdT6sLVXZghjpYmd/5p22osWYbVw42eEH565NrDxtu53OnyJoFuzVv/Ke76Kv1SqbEWvKsC3Ikdro60RGIy4ALsLF1gCKls2+cwqvGpgKXVDE4JiG8ai+xvJNCdCiIRoX8T60JII+whQSeiuWHoPN9rlp86/9fyjrnjjZ8LVM7zXCBnsPZklMb+cfVYqReSGFxDJTUPPba0KeEkvV0nXsy3MLggdBsPnmWU8S1VkQ40Wd6VtCWf1H4l2rvJW7Eey5xruR+BlZhgLo9m/+yuzWGSfOcokQ3NAKmyzqu5ZVOHlJQ81HFge+xa9HcP6MtXCONsQOG5RpocRr2II5wV6++ZrIWG7yZXthdMvKMIqRI4U20=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
