language: ruby
install:
- bundle update --bundler
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  - provider: codedeploy
    bucket: codedeploy-checo-portfolio-us-east-1
    bundle_type: zip
    application: checo-portfolio
    key: development/latest/source.zip
    deployment_group: development
    region: us-east-1
    on:
      branch: develop
  - provider: codedeploy
    bucket: codedeploy-checo-portfolio-us-east-1
    bundle_type: zip
    application: checo-portfolio
    key: production/latest/source.zip
    deployment_group: production
    region: us-east-1
    on:
      branch: master
