language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: NhKGjniDdUTKgQQHn8J2RE5DzFhC9EwDKViU4SuUuaUGCjYiELx2To12uHp1xq2twfPk8bv9b98jCTIhcu9nTE5Ia+HwMu/o31WT1krbRHNv7V5UFG+wtES6QtT638GbAIfcOD0IO8njWUR0GLM0N0EYHbPKw5xCznJfT3cHRNADSvgbq//WpI+wj8gEoRzHCpK9PbQ7m+zMlkCMoKuUZbbdCx3tWSTnbycsyHESfspONFM0hPNJ8RuWQcln2jO7JDvs96ocHjAMe7ij8fytjy6WjRYMT+u/L8eMKxsT+stZk5QzKAE81FpgE5A8JQY+6jsijXGLRnQ90FnGYegM8Wv7u/y/R3gz/4sKEEj4NY7YQ2tuRLJFsQnUBFGtUYtnyM/qvHupgiXF/VABtHTHFrEEmWkA9bb9u2ufWaUkRgd8oJN6hAkB1+yfxz0KLeP3FU9gs6fMseD4RsATcRJTwQMctw3tP9YlqHEErhgXjsQar4jC0TJqUdmOhsLjJdute/0DYWDJut2bzlNJIJGW958OFsJcHxDAKv2bYhQ6+syePR9pmdW94c+LW6GjTr2uDgJ0KupXVtGWoiq6jHFZJ95jzg+NWx4AmjZaDDotKZcuAvgIiZY/HyRhZ/UCUedwhQBmWYo9K+mMD9gWxfg+fR8sOI/YyxVpl3Ks5x5AJk0=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
