language: ruby
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: GKXUmRwQSLLpR0FSrzbeRTebU+ybBtAyytP8fnzsdF5wWhEqCX4lFoXn+yayZupMKjBmEol18s5qqJviuSRqeDN+Iccn4y4rGg0QxYy1fegmlbak+beLqv/iDKhLpDboN13khafNuC00JOIPtUZtXNGJhCYVjLYBA8++MoEGPNaBa/o5RPud+hgT90mYeBV+PWoY69XUbqAslkYzliR917SLTbpWN3WJmwE3K/dPhixNDJLqlWa+NDWL9qbXOMAReHlzmMeRL4HrGHpnuQziqeNsXr3GKU7mCDt5j6uvfoX2b1eKRUUbbmSHB2ItR/0mIMeWuDtGMFVo46TxlXQe27g1JmWa3XB8PvmGn7nHEI4GkDmbitAGywL5YzdIJ1Xx0XoP3A5T5CJECXxW2y9e8RBOdM4IB6BjZxeIiE3vqzv7YKfMY0AUOBZmo4gaYu1do4ux1EvzV/fEfEnuc2kSJ8smXS0p7B3iiISB32dS1AenPvtsWiSUfGLjmLIfaRKYIxr0uAhp4fJvcWsU80WyhGHUKDEWU/6nHIh+DOkVlKOHFV6QbTLhhl0XYc7bfscRuVkXwegsbb9g8ur182JH4LEotoZteHdUo16SyNAvSy5/BnAPWk1kWK4LfUUVFzPD30/GuougQQfsd4AJwnNhgnxH++WRuaS/zb7MF71pEkI=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
