language: ruby
cache: bundler
rvm:
  2.4.1
services:
  postgresql
addons:
  chrome: stable
before_script:
  - bundle exec rake db:create
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
deploy:
  provider: heroku
  api_key:
    secure: OA3YC6UyoTLKQg4vj7dD0yahT0xzSBjBXVsFwFque+h5JcukjVwcA2tHzOWS6oUzK0xM3/UX3MOpXUzg/48w6SdY2MHOFibf039eB1dHdOScxZOJNXXTJk4G734yJWvy+cDjPY4MwmaLwDvKq4KiZgyF6iMv8OK3xwdNpbImRs2aJD2AeFV2rdlQgmjpgB88qFLmtGPyNMO3bCA3VP0CL9zE3kYBsihkhrIfnrh7Re9g504E925TltSX4lktjzjl0TCz+Mc3st7EH6qfHOUtXcK1bmV+poXm8OzQWwlCfWpvVeqHgH9tSEd8DGxwzofiFDX/FKi/dqyDA8muc/s9NhMVuCpL0IPioUqbsskfrg0NTcuNCVCpgj0x3rTXDnX05fOgyosLHlK+5yv8OJuIOq7CXc/wwwo8KvhVoqaoSCDt2i/1k2EJcBAnUON/whMBCXptN4EEJ9bhoWxs4Ca9vwIZVx174hcE4byuiTcpKhKZ9EwRpCQoBs9cZCoooMfKg5QHhfaII+ws/hiQUf3iT/B+RwOh1E7te3Mlio+1AnhTOeWqgE8TqPO/DB8RRdx7fccH0cWHIyXFDLfdAqeTvol1daOoQ3x0AEww2u+BNKci1SAgGNMIv6ZNxqWZie7LpgV4xP+PsQ2DZ6qWoTmGW3SJAWssTGjVRzBCjRVu8qM=
  app: portfolio-website
  on:
    repo: kcheco/portfolio-website
