language: ruby
install:
  - bundle update --bundler
cache: bundler
rvm: 2.4.1
services: postgresql
addons:
  chrome: stable
before_script:
- bundle exec rake db:create
script:
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
deploy:
  provider: heroku
  api_key:
    secure: ougygW+fk2AivNVRc9wx7uLb2ukHii2s3/ZKhZCb0RfgjgDdcs2kA8kdXDaGujvOzwkAqQpjGqS0WCYv8NdULoT0v6592oOuY9o7XeuahsQlF4W8N054p64Cpquk1U8FjwpN16B1/sj/Tsn95Z4FIdBLKRNRd3MGISo7iXUx9hSHafvrH2B8zfFo6STfOTaUoAIRGhXMVVOBU3/Olw4ilVFwA8mKmoYtTu48Je8ZDXy1CG8QtHl5NIGe7oy/POx17GWRJfxgfmjdL+DhXHXE/cxm286Dib9h/d56slTV2A3WEoj+2zUXgGkpArf9Q+Sy6g7zO6nFJunPZ8wqh3MBB9CcP+DqpcMwLXX15vLSU7fNv7dr0I6zDepIpAIBnA8YQu+gEJVnXySRi2wxXN/34uQ1qyw5d2LbMbKcnNWPgTxzcIUiYbmpDYtNhgQ5zKkPe8bBN76LlucFLUyBJ0Q3/OfPm9Qjcrcvbf4aPwUIqwt8U1WViYUBRwFyXcb0YUtGbjdRcFo33nw+XektFtO6JcbyXLZ8EdW6+mjt9vK06jWnH19AEMGn0zZG9kNXHCrPsmEwfVvh0u4lTLQK/h7tqh4YojahwHRnDXI1IcXuffFhsKsxRbH/5H4H2FLQ2lB4nukBhbwklW3eaccFWmyAHIHbXmIeoXOCX+DCBSgE36o=
  app: checo-portfolio-website
  on:
    repo: kcheco/portfolio-website
