version: 0.0
os: linux
files:
  - source: /
  - destination: /home/ubuntu/code/
hooks:
  BeforeInstall:
    - location: scripts/build-app-image
    # - location: scripts/install-docker
  AfterInstall:
    # - location: scripts/build-app-image
  ApplicationStart:
