version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install-docker
    - location: scripts/rootless-docker
  AfterInstall:
    - location: scripts/build-app-image
  ApplicationStart:
