version: '3.8'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/checo-portfolio
      - type: tmpfs
        target: /checo-portfolio/tmp/pids/
    ports:
      - "3000:3000"
    depends_on:
      - db