version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/production/Dockerfile
    volumes:
      - ./:/home/app/checo-portfolio/
    ports:
      - "80:80"
      - "443:443"