#!/bin/bash
apt-get install -y uidmap
dockerd-rootless-setuptool.sh uninstall
apt-get install -y docker-ce-rootless-extras
dockerd-rootless-setuptool.sh install

export PATH=/usr/bin:$PATH
export DOCKER_HOST=unix:///run/user/1000/docker.sock